# Model Arguments
model:
  _component_: torchtune.models.llama2.qlora_llama2_7b
  lora_attn_modules: ["q_proj", "v_proj", "k_proj", "output_proj"]
  apply_lora_to_mlp: True
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /home/trodrigues/tiago/llama2-7b/tokenizer.model

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.instruct_dataset
  source: theKrypt0/Finetune-Llama-Instruct
  split: train
  train_on_input: True
  template: torchtune.data._instruct_templates.DefaultInstruct
  max_seq_len: 8192
seed: 42
shuffle: True

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /home/trodrigues/tiago/llama2-7b/
  checkpoint_files:
    [pytorch_model-00001-of-00002.bin, pytorch_model-00002-of-00002.bin]
  adapter_checkpoint: null
  recipe_checkpoint: null
  output_dir: /home/trodrigues/tiago/llama2-7b/
  model_type: LLAMA2
resume_from_checkpoint: False

# Optimizer, Scheduler, and Loss
optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5

lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torch.nn.CrossEntropyLoss

# Fine-tuning Arguments
epochs: 2
batch_size: 1
max_steps_per_epoch: null
gradient_accumulation_steps: 4
compile: False

# Training Env
device: cuda

# Reduced Precision
dtype: bf16

# Memory management
enable_activation_checkpointing: True

# Logging
output_dir: /tmp/qlora_finetune_output_llama/
metric_logger:
  _component_: torchtune.utils.metric_logging.WandBLogger
  log_dir: ${output_dir}
  project: finetune-llms-summarization
log_every_n_steps: null

# Show case the usage of pytorch profiler
# Set enabled to False as it's only needed for debugging training
profiler:
  _component_: torchtune.utils.profiler
  enabled: False
  output_dir: ${output_dir}/torchtune_perf_tracing.json
